# action.yml
name: 'Prefapp helm state updater'
description: 'Github action that updates helm state repo using prefapp/prefapp-cicdpy docker image'
inputs:
  file-path:
    description: 'Path to target yaml file'
    required: true
  key:
    description: 'Target key in yaml'
    required: true
    default: '/example/target/key'
  value:
    description: 'Final value for key field'
    required: true
  git-state-repo:
    description: 'Path to git repo'
    required: true
  git-user:
    description: 'Git user'
    required: true
  git-mail:
    description: 'Git mail'
    required: true
  git-remote:
    description: 'Git remote'
    required: false
    default: 'origin'
  git-branch:
    description: 'Git branch'
    required: false
    default: 'master'
  commit-message:
    description: 'Git commit message'
    required: true


runs:
  using: 'composite'
  steps:
    - run: |
        docker run -v $(pwd):/mnt prefapp/prefapp-cicdpy valores.modificar fichero=/mnt/${{ inputs.file-path }} key=${{ inputs.key }} valor=${{ inputs.value }} sobreescribir=1

      shell: bash

    - run: |
        ls -l 
        cd ${{ inputs.git-state-repo }}
        ls -lah
        echo "GIT CONFIG"
        echo 'git config user.name ${{ inputs.git-user }}'
        git config user.name ${{ inputs.git-user }}
        echo 'git config user.email ${{ inputs.git-mail }}'
        echo "GIT STATUS"
        git status .
        echo "GIT ADD"
        git add ${{ inputs.file-path }}
        git status
        echo "GIT COMMIT"
        echo git commit -m ${{ inputs.commit-message }}
        git commit -m "${{ inputs.commit-message }}"
        echo "GIT PUSH"
        git push ${{ inputs.git-remote }} ${{ inputs.git-branch }}

      shell: bash
